name: Format Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc # Run with latest stable Deno.
      - name: Run Format Check
        run: |
          deno install
          deno task format:check
