name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc # Run with latest stable Deno.
      
      - name: Install dependencies
        run: deno install

      - name: Run tests
        run: deno task test
