name: Type Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc # Run with latest stable Deno.

      - name: Install dependencies
        run: deno install

      - name: Build
        run: deno task build

      - name: Run type-checks
        run: deno task check
